### ISSUE TITLE
[FEAT] 티켓북 삭제 기능 구현 및 레이아웃 오류 해결

### ISSUE THREAD

**Issue by hwangJi-dev** [TeamARtique/ARtique-iOS#100]
## 📌  Feature Issue
-  티켓북 삭제 기능 구현 및 레이아웃 오류 해결

## 📝  To-do
- [ ] 티켓북 삭제 UI 구현
- [ ] 티켓북 삭제 API 연결
- [ ] 티켓북 UI 오류 해결
