### ISSUE TITLE
[HOTFIX] 이미지 업로드 기능 구현 & 엑세스토큰 갱신 처리 & 로딩뷰 추가

### ISSUE THREAD

**Issue by hwangJi-dev** [TeamARtique/ARtique-iOS#106]
## 📌  Feature Issue
- Firebase sdk를 이용한 Firebase Storage에 이미지 업로드 기능 구현

## 📝  To-do
- [x] Firebase sdk 설치
- [x] Firebase Storage에 이미지 업로드
- [x] 업로드된 image URL 확인
- [x] 전시 등록 네트워크 코드 수정
- [x] 전시 등록 잘 돌아가는지 확인
- [x] 엑세스토큰 갱신 일괄 처리
- [x] 로딩뷰 UI 구현
- [x] network 코드들에 일괄적으로 로딩뷰 심기
