### ISSUE TITLE
[CHORE] 홈화면 디자인 수정사항

### ISSUE THREAD

**Issue by yunkyung-Hwang** [TeamARtique/ARtique-iOS#11]
## 📝  To-do

- [ ] 스크롤할 때, 로고 부분 스무스하게 올라가기
- [x] 상단 - 검색, 티켓북 아이콘 변경
- [x] 카테고리 폰트 변경(선택된 항목: Bold, 그냥: Regular)
- [x] 테이블 뷰 셀 선택 안되게하기
