### ISSUE TITLE
[HOTFIX] 티켓북 자잘한 오류/버그들 수정 및 기능 추가

### ISSUE THREAD

**Issue by hwangJi-dev** [TeamARtique/ARtique-iOS#113]
## 📌  Feature Issue
- 티켓북 자잘한 오류/버그들 수정

## 📝  To-do
- [x] ARScene에서 모달로 띄워질 때 네비타입 수정
- [x] 티켓북 네비바 상단 투명한 현상 해결
- [x] 스크롤 애니메이션 추가
