### ISSUE TITLE
[FEAT] AR 기능 추가 (title, 아트워크 상세보기 기능, 조명 수정)

### ISSUE THREAD

**Issue by hwangJi-dev** [TeamARtique/ARtique-iOS#116]
## 📌  Feature Issue
 AR 기능 추가 (title, 아트워크 상세보기 기능, 조명 수정)

## 📝  To-do
- [ ] 12개 모델 title 추가
- [x] 5개, 12개, 30개 모두 아트워크에 TapGesture 추가
- [x] 작품 클릭시 halfModalView를 띄워서 작품 설명 보이게 하기
- [ ] 조명 밝기 조절하기
