### ISSUE TITLE
[REFACTOR] AR 전시 모델 리펙토링

### ISSUE THREAD

**Issue by hwangJi-dev** [TeamARtique/ARtique-iOS#120]
### 📝 todo
 - [x] 조명 세기 조절
 - [x] 12개 모델 title 심기
 - [x] 알럿 수정사항 반영
