### ISSUE TITLE
[FEAT] 전시 등록 프로세스 UI

### ISSUE THREAD

**Issue by yunkyung-Hwang** [TeamARtique/ARtique-iOS#24]
## 📌  Feature Issue
전시 등록 프로세스 UI 구현

## 📝  To-do

- [x] 프로그레스바 & 네비바
- [x] 사진 개수 & 테마 선택 뷰
- [ ] 사진 선택 뷰
- [ ] 순서 조정 뷰
- [ ] 작품 설명 추가 뷰
- [ ] 전시 세부사항 입력 뷰
