### ISSUE TITLE
[FEAT] 전시 등록 갤러리 뷰

### ISSUE THREAD

**Issue by yunkyung-Hwang** [TeamARtique/ARtique-iOS#31]
## 📌  Feature Issue
전시 등록 갤러리 뷰 기능 추가

## 📝  To-do

- [x] preview imageView 이미지 크기 조절 두손가락 터치 액션 추가
- [ ] 편집한 이미지 상태로 모델에 저장
- [x] 최대 개수 초과 선택 시 preview 이미지는 바뀌게 수정
- [x] 앨범 목록 연결 후 순서 정렬
- [x] PHAsset, image 화질 개선
