### ISSUE TITLE
[CHORE] 전시 상세 뷰 디자인 변경

### ISSUE THREAD

**Issue by yunkyung-Hwang** [TeamARtique/ARtique-iOS#32]
## 📌  Feature Issue
전시 상세 뷰 디자인 변경

## 📝  To-do

- [x] 네비바 타이틀 변경
- [x] 레이아웃 변경
- [x] 베이스 스크롤뷰 추가
- [x] 공유 버튼 이벤트 구현
