### ISSUE TITLE
[FEAT] 메인뷰 + 전시상세뷰 프로토 구현

### ISSUE THREAD

**Issue by yunkyung-Hwang** [TeamARtique/ARtique-iOS#4]
## 📌  Feature Issue

메인뷰 + 전시상세뷰 프로토 구현

## 📝  To-do

- [x] - 상단 탭바
- [x] 네비바 스크롤시 숨기기
- [ ] 상하 스크롤
- [ ] 전시 목록 구성
- [ ] 전시 클릭 화면 이동
- [ ] 앱아이콘, 로고, 스플래시뷰 적용
- [ ] 좋아요, 북마크 버튼
- [ ] 전시 상세 화면
