### ISSUE TITLE
[FEAT] 전시 목록 뷰 UI

### ISSUE THREAD

**Issue by yunkyung-Hwang** [TeamARtique/ARtique-iOS#42]
## 📌  Feature Issue
홈, 마이페이지 전시 목록 뷰 UI 구현

## 📝  To-do

- [x] 전시 목록 xib 생성
- [x] 마이페이지 - 등록한 전시
- [x] 마이페이지 - 북마크한 전시
- [x] 홈 - 전체 전시
