### ISSUE TITLE
[ADD] 마이페이지 기능 수정 및 추가

### ISSUE THREAD

**Issue by yunkyung-Hwang** [TeamARtique/ARtique-iOS#46]
## 📌  Feature Issue
마이페이지 기능 수정 및 추가

## 📝  To-do

- [x] 마이페이지 컴포넌트 수정
- [x] 등록, 북마크한 전시가 없을때 상황별 화면 수정
- [x] 등록한 전시가 없을때 화면 구현 및 연결
- [x] 프로필 수정 완료버튼 활성화 상태 조절
