### ISSUE TITLE
[CHORE] 홈화면 디자인 수정

### ISSUE THREAD

**Issue by yunkyung-Hwang** [TeamARtique/ARtique-iOS#48]
## 📌  Feature Issue
홈화면 디자인 수정

## 📝  To-do

- [x] 카테고리 변경 현대미술 -> 전문예술
- [x] 카테고리 indicator bar 디자인 수정
- [x] 폰트 변경
- [x] 레이아웃 변경
- [x] 탭바 Add 탭 디자인 수정
