### ISSUE TITLE
[FIX] 전시 등록 프로세스 버그 수정

### ISSUE THREAD

**Issue by yunkyung-Hwang** [TeamARtique/ARtique-iOS#60]
## 📌  Feature Issue
전시 등록 프로세스 버그 수정

## 📝  To-do

- [x] exhibition Model 수정

사진 선택 뷰
- [x] 선택 해제
- [x] 선택 사진 넘버링
- [x] 다음 버튼 crop binding
- [x] 로딩 시간 초과 시 action 추가

설명 입력 뷰
- [x] 키보드 show/hide에 따른 스크롤
