### ISSUE TITLE
[ADD] 자잘한 디자인 수정 반영 및 코드 추가

### ISSUE THREAD

**Issue by yunkyung-Hwang** [TeamARtique/ARtique-iOS#76]
## 📌  Feature Issue
자잘한 디자인 수정 반영 및 코드 추가

## 📝  To-do
- [ ] 토스트 메세지 뷰 추가
- [ ] 등록 alret 추가 및 메세지, 버튼 수정
- [ ] 입력에 따른 화면 스크롤 추가
- [ ] textView 줄 수 지정
- [ ] 앨범 선택 화면 디자인 수정
- [ ] 포스터 제목, 작가, 날짜 좌우 여백값 수정
- [ ] 포스터 디자인 수정 반영 (폰트 사이즈, 배경색 변경)
- [ ] 전시 등록 프로세스 리펙토링
- [ ] 전시 등록 필수 값 지정
- [ ] 전시 상세 뷰 터치 시 화면 변경 추가
