### ISSUE TITLE
[FEAT] 포스터 변경 뷰 구현 및 선택 뷰 refactor

### ISSUE THREAD

**Issue by yunkyung-Hwang** [TeamARtique/ARtique-iOS#95]
## 📌  Feature Issue
사진 선택 화면 구조 수정 및 기능 추가
포스터 변경 뷰 구현

## 📝  To-do

- [ ] 사진 선택 뷰 공통 부분 정리
- [x] 사진 재선택 => 편집 & 선택된 상태에서 재선택 => 선택 해제
- [x] 사진 선택 드래그 편집 에러 해결
- [x] 포스터 변경 뷰 구현
